# Generated by Django 5.1.1 on 2024-11-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('point', models.BigIntegerField(default=0)),
                ('last_signin', models.DateField(auto_now=True)),
            ],
        ),
    ]
